# Generated by Django 5.0.1 on 2024-01-10 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
